all_majors = (
        'African and African American Studies',
        'American Studies', 
        'Applied Computing Minor', 
        'Art Education',
        'Biochemistry', 
        'Bioinformatics',
        'Biology',
        'Biotechnology', 
        'Business Administration',
        'Chemistry',
        'Computer Engineering',
        'Computer Science', 
        'Creative Writing', 
        'Criminal Justice',
        'Digital Design',
        'Drama', 
        'Early Childhood Education', 
        'Elementary Education',
        'English', 
        'English Education', 
        'Environmental Science', 
        'Foreign Language', 
        'Gender Studies',
        'Human Performance and Recreation', 
        'Management', 
        'Management Information Science',
        'Marketing',
        'Mass Communications',
        'Mathematics',
        'Mathematics Education', 
        'Middle Level Education', 
        'Music',
        'Music Education', 
        'Organizational Management', 
        'Performing Ensembles',
        'Philosophy and Religion', 
        'PK-12 and Secondary Education Programs', 
        'Political Science', 
        'Psychology', 
        'RN to BSN in Nursing', 
        'Sociology', 
        'Sport Management', 
        'Studio Art', 
)